# Generated by Django 3.2.8 on 2021-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='dur',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='event',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='start',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='timeleft',
            field=models.CharField(max_length=200),
        ),
    ]
