# Generated by Django 3.2.8 on 2021-12-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211203_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200)),
                ('dur', models.CharField(max_length=200)),
                ('timeleft', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='APIData',
        ),
    ]
